### ISSUE TITLE
Any custom fonts?

### ISSUE THREAD

**Issue by 0leg5ergeev** [tkrkt/text2png#1]
Hi, how can I add a new font to txt2pic? I saw node-canvas has function like this:
`Canvas.registerFont('fonts/Lobster-Regular.ttf', {family: 'Lobster'});`

but how can I get it in txt2pic?

**Comment by tkrkt** [comment]
Canvas.registerFont is only available with node-canvas 2.x, but it is still in alpha version. text2png will support ``registerFont`` when node-canvas 2.0 is released.

**Comment by tkrkt** [comment]
node-canvas 2.0 has not been released yet, so I released text2png as beta.
Please use `npm install text2png@next` and try this.

```js
text2png('with custom fonts', {
  font: '50px Lobster',
  localFontPath: 'fonts/Lobstar-Regular.ttf',
  localFontName: 'Lobster'
});
```

Sorry for keep you waiting.

**Comment by tkrkt** [comment]
i close this issue because node-canvas 2.0 was officially released.
