### ISSUE TITLE
hexadecimal for colors

### ISSUE THREAD

**Issue by paulahfaria** [tkrkt/text2png#21]
Hey :)
Is there any way to use hexadecimal for color/backgroundColor options?

**Comment by tkrkt** [comment]
Yes. You can use CSS color style.

* #000
* rgb(0,0,0)
* black

**Comment by paulahfaria** [comment]
It worked! But only with rgb option.
Thank you :)

**Comment by paulahfaria** [comment]
It worked! But only with rgb option.
Thank you :)
