### ISSUE TITLE
Stroke

### ISSUE THREAD

**Issue by philipeachille** [tkrkt/text2png#37]
Thanks for the easy to use module. 

Would it possible for you to add stroke options to the module (width and color)?

Best PAV

**Comment by tkrkt** [comment]
If you give me PR, I’d be happy to merge it.
Fork this as your repository, create a branch, push code, and create a PR.
It's ok to make mistakes!

**Comment by philipeachille** [comment]
I get an error when trying to push: "remote: Permission to tkrkt/text2png.git denied to philipeachille."

**Comment by tkrkt** [comment]
First you need to fork this repository.

https://hisham.hm/2016/01/01/how-to-make-a-pull-request-on-github-a-quick-tutorial/

(I should write guidelines for repository contributors...)

**Comment by philipeachille** [comment]
thanks for the link, I now created the pull request
