### ISSUE TITLE
Fontconfig error: Cannot load default config file

### ISSUE THREAD

**Issue by MeowcaTheoRange** [tkrkt/text2png#44]
I don't know how to solve this.
All my code is using this is 
`fs.writeFileSync('image2.png', text2png(msg.content.replace(/```/gi, ""), {
        	font: '16px monospace',
	        lineSpacing: 6,
	        color: 'lime',
      	  backgroundColor: 'black',
  	      padding: 16
        }));`
I am using repl.it with a node-v8 enviroment.

**Comment by autowert66** [comment]
As far as I know this is because REPLIT has no fonts installed. 
You could try to [install a font manually](https://medium.com/source-words/how-to-manually-install-update-and-uninstall-fonts-on-linux-a8d09a3853b0).
