### ISSUE TITLE
Border around entire image?

### ISSUE THREAD

**Issue by NoobDoesMC** [tkrkt/text2png#5]
I don't think it's currently supported.

Is there a possibility of adding this?

And with current builds how can I workaround and add a thick border around the png?

**Comment by tkrkt** [comment]
please use `text2png@next`.
It supports `borderWidth` and `borderColor` (and `borderLeftWidth` and ...) for simple border.

```js
text2png('with border', {
  color: 'navy',
  backgroundColor: 'lightblue',
  borderColor: 'navy',
  borderWidth: 5,
  padding: 5
});
```

![out](https://user-images.githubusercontent.com/8198831/36403934-403f396c-162b-11e8-9d54-53c113982632.png)

if you want to use complex border, you can get node-canvas object(`output: canvas`) and decorate it yourself.

**Comment by tkrkt** [comment]
i close this issue because node-canvas 2.0 was officially released.
